sudo: required
services:
- docker
# Caching based on http://rundef.com/fast-travis-ci-docker-build
cache:
  directories:
  - "$CACHE_DIR"
before_install:
- if [ -f ${CACHE_FILE_PDFLATEX} ]; then gunzip -c ${CACHE_FILE_PDFLATEX} | docker
  load; fi
env:
  global:
  - CACHE_DIR=$HOME/.cache/docker/images
  - CACHE_FILE_PDFLATEX=$CACHE_DIR/pdflatex.tar.gz
install:
# docker run and build commands
- mkdir -p $CACHE_DIR
- if [ ! -f ${CACHE_FILE_PDFLATEX} ]; then docker pull jonathanlking/pdflatex-base:latest
  && docker save jonathanlking/pdflatex-base:latest | gzip > ${CACHE_FILE_PDFLATEX};
  fi
script:
- mkdir _build && cd tex
- docker run --rm -v "$PWD":/usr/src/project -w /usr/src/project jonathanlking/pdflatex-base
  /bin/bash -c 'pdflatex topic5.tex && pdflatex topic5.tex'
- cp topic5.pdf ../_build/topic5.pdf
- cd ../
deploy:
  - provider: s3
    access_key_id: AKIAJAZMF2XELR6XWO4A
    secret_access_key:
      secure: QwvgnE/qPa2JcsBJ7Gz18gNkU7BpUIKBCaqSAA7atHweWNqEDiuPVlpgIE9bkNwJ2rc6GEDw1crsyNn7ve6sKmq/xwP9XJxOIcDYcRnoBfxZ9jkxPPoDgxqGkiiU8H/H5BPj0lS+JdmWM2kaLI7GhJYDw1A7gYNn06f3+ieBfnYlYBFgOymD98k/4dQHADyJLAPzdVdI2hJeo6fUqb2W1ynFoxDjJcQ5+8V3LQT1PqTl+6S1hW8U1BBLnaI6g3uygAhZL1izKU/W+Qw+kEtNMRfvlmWJCQbMVHjpfozAWZw+orpj/TFMFtXSeN9XM4aNHHFcTls2bt5CGw3lP2hM8tCOeToHdzModcqImfxi3wsswnlGGfZAgEHHgvQvz/e+dqKq5M9PGg381ZRCd9FinJ1SrAAlTjCuh9/xL5hrwjIA7GgjDz/YY59pGChRFwAgpy/kw+4MOU/NJQVjym7NbktrTYktVGTRygLf6GLyJPmaS0HpQ9ElZpde0CSPRH4s3RE+fYn4JBDCxhPIJZ7o3O+5T6OaWz9zhZE7Zi/CuRZlAEcfI4/NXErEfB4NOONWbWohqXRdnAzWIvyDsb1QpzbUqAtwRoVg1LpRTMW3zpWkcK7iRhkYmcpo/ENNOJriz/Wq+4w6cvM3cpvL+k5q2PWh0mWD2aMT/Wi+lahWTYE=
    bucket: s3.jlk.co
    region: eu-west-2
    local-dir: _build
    upload-dir: sei
    acl: public_read
    skip_cleanup: true
    on:
      all_branches: true
      branch: release
      repo: jonathanlking/sei-topic-5
  - provider: releases
    api_key:
      secure: pbmQJZV0H2bnJZuBlU+8sZqnBzE3qpunY2Bf7zv5z4Kps7mL3m9Bt1ebmLKTq8nl1QtDrJ53dwcOiJrEtMWAlsZIAYOcIslBzlKMq8+Zdd+yFlxyWmptHWLHGaV0REJwgGSj+dGv1JmyMCYy3Jv/ZDfhAhnvRTi88c1POVm3KFGT/eLCVJZfw+9m2y8K/ug0pZe8Beif85IEMzdf5Lf88Sn2FAQp2fM5BGHkaTJf5/2ILnJHRamg+Cyn1LRt9L+Oak3/SoDhLzDqwYkHwBS2GwfWR1yIuUXItIq6HvCZU0ukjbfnj8fQPKgmbc/aIxTGZSmYc4Ty4C+hxkbEMEwqIjqCIiq5a16NcHLdiR6cnpjm0tybv9Vyzc0v0mDNUZRZIc8pvnt2nV3ccFjzhwXNJajiLCxdz83qH/DM1Yj1gCKXd9OEn6ZiKAmRwY4wse31dLXvr8JmyGIfV+5PjaNoLcAtRHofmJCrn0d1+LM5alYCT/izz/Trm2Hsg15+P9yjomzR9FCCWwhVQt74b4sgO/vyjREWsVhmJOptthVbeZF+QWJPKcPSe31tbC9L6sx5MGNXq4A65RShRQ6t4Dy5xKAJHEFnsuHkb99LyDY6VK1ow5ODVzntZYL1A/YxTa6P0aaY56BdR/1O9yCDQd098J706RsmB5ASNd3TMH7LH1g=
    file: _build/topic5.pdf
    skip_cleanup: true
    on:
      repo: jonathanlking/sei-topic-5
      branch: release
      tags: true
