title: LaTeX Continuous Delivery ⚡
description: Report for Software Engineering for Industry topic 5 - Continuous Delivery
author: Elliot Greenwood and Jonathan King
email: "{eg1514, jlk14}@ic.ac.uk"
